# Cross compilation environment for bliss-anlyser

FROM ubuntu:24.04

RUN apt-get update

RUN apt-get install -y curl git pkg-config
RUN apt-get install -y build-essential yasm clang

RUN apt-get install -y libavutil-dev libavcodec-dev libavformat-dev \
                       libavfilter-dev libavdevice-dev libswresample-dev libfftw3-dev \
                       ffmpeg

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin/:${PATH}"

RUN mkdir /build
ENV CARGO_TARGET_DIR /build
ENV CARGO_HOME /build/cache

RUN mkdir /src

WORKDIR /src
CMD ["/src/docker/docker-build-x86-libav.sh"]

