name: Build for all platforms

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux_x86_ffmpeg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build x86
      run: |
        docker build -t bliss-analyser-x86-ffmpeg - < docker/Dockerfile_x86_ffmpeg
        docker run --rm -v $PWD/target:/build -v $PWD:/src bliss-analyser-x86-ffmpeg

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bliss-analyser-linux-x86-ffmpeg
        path: releases/
