name: macOS

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  macOS:
    runs-on: macos-11.0

    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install deps
      run: |
          brew install ffmpeg@5

    - name: Build
      run: |
        mkdir releases
        cargo build --release
        strip target/release/bliss-analyser
        cp target/release/bliss-analyser releases/bliss-analyser
        ls -alR /usr/local/Cellar/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bliss-analyser-mac
        path: releases/
